CREATE TABLE `users` (
     `id` int(11) NOT NULL AUTO_INCREMENT,
     `date` datetime NOT NULL,
     `updated` datetime NOT NULL,
     `companyId` int(11) DEFAULT NULL,
     `email` varchar(255) NOT NULL,
     `password` varchar(60) DEFAULT NULL,
     `isActive` tinyint(1) DEFAULT '1',
     `autoLoginToken` varchar(40) DEFAULT NULL,
     `autoLoginIdentifier` varchar(40) DEFAULT NULL,
     `lastLogin` datetime DEFAULT NULL,
     `access` varchar(45) NOT NULL DEFAULT 'User',
     `gender` varchar(16) NOT NULL DEFAULT 'Male',
     `firstName` varchar(255) DEFAULT NULL,
     `lastName` varchar(255) DEFAULT NULL,
     `state` varchar(45) DEFAULT 'Created',
     `config` text,
     `initials` varchar(8) DEFAULT NULL,
     `lastClick` datetime DEFAULT NULL,
     `mobile` varchar(255) DEFAULT NULL,
     `phone` varchar(255) DEFAULT NULL,
     `street` varchar(255) DEFAULT NULL,
     `zipcode` varchar(45) DEFAULT NULL,
     `city` varchar(255) DEFAULT NULL,
     `country` varchar(255) DEFAULT NULL,
     `dateOfBirth` date DEFAULT NULL,
     PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
